"""initial

Revision ID: cea4674a8ad3
Revises: 
Create Date: 2025-10-02 17:36:08.074288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea4674a8ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasons', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('ranking')
        batch_op.drop_column('score')
        batch_op.drop_column('reasons')

    # ### end Alembic commands ###
